/**
 * Favicon Package Generator
 * Creates a ZIP file containing all favicon assets and configuration files.
 */

import JSZip from 'jszip';
import type { RenderedImage } from './svg-renderer';
import { encodePngsToIco } from './ico-encoder';

export interface FaviconPackageOptions {
    images: RenderedImage[];
    siteName?: string;
}

const WEBMANIFEST_TEMPLATE = (siteName: string) =>
    JSON.stringify(
        {
            name: siteName,
            short_name: siteName,
            icons: [
                {
                    src: '/android-chrome-192x192.png',
                    sizes: '192x192',
                    type: 'image/png',
                },
                {
                    src: '/android-chrome-512x512.png',
                    sizes: '512x512',
                    type: 'image/png',
                },
            ],
            theme_color: '#ffffff',
            background_color: '#ffffff',
            display: 'standalone',
        },
        null,
        2
    );

const HTML_SNIPPET = `<!-- Favicon Tags – paste inside <head> -->
<link rel="icon" type="image/x-icon" href="/favicon.ico" />
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
<link rel="manifest" href="/site.webmanifest" />`;

export function getHtmlSnippet(): string {
    return HTML_SNIPPET;
}

/**
 * Generate the full favicon package as a downloadable ZIP blob.
 */
export async function generateFaviconPackage(
    options: FaviconPackageOptions
): Promise<Blob> {
    const { images, siteName = 'My App' } = options;
    const zip = new JSZip();

    // Generate .ico from smaller sizes (16, 32, 48)
    const icoSizes = [16, 32, 48];
    const icoPngs = images
        .filter((img) => icoSizes.includes(img.size))
        .map((img) => ({ size: img.size, blob: img.blob }));

    if (icoPngs.length > 0) {
        const icoBlob = await encodePngsToIco(icoPngs);
        zip.file('favicon.ico', icoBlob);
    }

    // Add individual PNGs
    for (const img of images) {
        if (img.size === 180) {
            zip.file('apple-touch-icon.png', img.blob);
        }
        if (img.size === 192) {
            zip.file('android-chrome-192x192.png', img.blob);
        }
        if (img.size === 512) {
            zip.file('android-chrome-512x512.png', img.blob);
        }
        zip.file(`favicon-${img.size}x${img.size}.png`, img.blob);
    }

    // site.webmanifest
    zip.file('site.webmanifest', WEBMANIFEST_TEMPLATE(siteName));

    // HTML snippet
    zip.file('favicon-snippet.html', HTML_SNIPPET);

    // README
    zip.file(
        'README.md',
        `# Favicon Package

Generated by faviconverter.

## Usage

1. Copy all files to your project's \`public/\` directory.
2. Add the HTML snippet from \`favicon-snippet.html\` to your \`<head>\` tag.
3. That's it!

## Files Included

- \`favicon.ico\` – Multi-resolution ICO
- \`favicon-NxN.png\` – Individual PNG favicons
- \`apple-touch-icon.png\` – Apple Touch Icon (180×180)
- \`android-chrome-*.png\` – Android Chrome icons
- \`site.webmanifest\` – Web App Manifest
- \`favicon-snippet.html\` – Ready-to-paste HTML
`
    );

    return zip.generateAsync({ type: 'blob' });
}

/**
 * Generate only the ICO file from rendered images.
 */
export async function generateIcoOnly(
    images: RenderedImage[]
): Promise<Blob> {
    const icoSizes = [16, 32, 48, 64];
    const icoPngs = images
        .filter((img) => icoSizes.includes(img.size))
        .map((img) => ({ size: img.size, blob: img.blob }));

    if (icoPngs.length === 0) {
        // Fallback: use whatever sizes we have
        const fallback = images
            .filter((img) => img.size <= 256)
            .map((img) => ({ size: img.size, blob: img.blob }));
        return encodePngsToIco(fallback);
    }

    return encodePngsToIco(icoPngs);
}
